;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="AttributeSets",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.Armor",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.CharacterLevel",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.Damage",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.Gold",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.GoldBounty",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.Health",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.HealthRegenRate",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.Mana",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.ManaRegenRate",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.MaxHealth",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.MaxMana",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.MaxShield",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.MaxStamina",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.MoveSpeed",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.Shield",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.ShieldRegenRate",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.Stamina",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.StaminaRegenRate",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.XP",DevComment="")
+GameplayTagList=(Tag="AttributeSets.Base.SetByCaller.XPBounty",DevComment="")
+GameplayTagList=(Tag="Gameplay.Effect.RemoveOnDeath",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Dead",DevComment="")

